language: objective-c
osx_image: xcode8.3.1

before_install:
  - brew update
  - gem install xcpretty
  - gem install cocoapods
  - pod repo update --silent

install:
  - pod repo update
  - pod install

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace KataTODOAPIClient.xcworkspace -scheme 'KataTODOAPIClient' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
